name: Build and Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Package the app
        run: npm run package

      - name: Make installers
        run: npm run make

      - name: Publish the app
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npm run publish
